[package]
name = "file_watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
fs2 = "0.4.3"
log = "0.4.28"
regex = "1"
env_logger = "0.11.8"
clap = { version = "4.5.49", features = ["derive"] }
